version: '3'
services:
#  product-service:
#    build:
#      context: ./product-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - product-db
#
#  order-service:
#    build:
#      context: ./order-service
#    ports:
#      - "8081:8081"
#    depends_on:
#      - order-db
#
#  user-service:
#    build:
#      context: ./user-service
#    ports:
#      - "8082:8082"
#    depends_on:
#      - user-db

  product-db:
    container_name: product-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: fosrootpassword
      MYSQL_DATABASE: productdb
      MYSQL_USER: fosuser
      MYSQL_PASSWORD: fospassword


  order-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: fosrootpassword
      MYSQL_DATABASE: orderdb
      MYSQL_USER: fosuser
      MYSQL_PASSWORD: fospassword


  user-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: fosrootpassword
      MYSQL_DATABASE: userdb
      MYSQL_USER: fosuser
      MYSQL_PASSWORD: fospassword

