version: '3'
services:
  product-service:
    container_name: product-service
    build: ./product-service
    ports:
      - "8080:8080"
    env_file:
      - .env
#    depends_on:
#      - product-db

  order-service:
    container_name: order-service
    build: ./order-service
    ports:
      - "8081:8081"
    env_file:
      - .env
#    depends_on:
#      - order-db

  user-service:
    container_name: user-service
    build: ./user-service
    ports:
      - "8082:8082"
    env_file:
      - .env
#    depends_on:
#      - user-db

# UNCOMMENT BELOW DATABASES AND ABOVE depends_On AND CHANGE .env DB_URL TO USE THE DOCKERIZED MYSQL DBs

#  product-db:
#    container_name: product-db
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: ${PRODUCT_DB_PASSWORD}
#      MYSQL_DATABASE: fos-product-service
#      MYSQL_USER: ${PRODUCT_DB_USERNAME}
#      MYSQL_PASSWORD: ${PRODUCT_DB_PASSWORD}
#
#
#  order-db:
#    container_name: order-db
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: ${ORDER_DB_PASSWORD}
#      MYSQL_DATABASE: fos-order-service
#      MYSQL_USER: ${ORDER_DB_USERNAME}
#      MYSQL_PASSWORD: ${ORDER_DB_PASSWORD}
#
#
#  user-db:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: ${USER_DB_PASSWORD}
#      MYSQL_DATABASE: for-user-service
#      MYSQL_USER: ${USER_DB_USERNAME}
#      MYSQL_PASSWORD: ${USER_DB_PASSWORD}

