version: '3'
services:
  product-service:
    container_name: product-service
    build: ./product-service
    ports:
      - "8080:8080"
    env_file:
      - .env
#    depends_on:
#      - product-db
#
  order-service:
    container_name: order-service
    build: ./order-service
    ports:
      - "8081:8081"
    env_file:
      - .env
#    depends_on:
#      - order-db

  user-service:
    container_name: user-service
    build: ./user-service
    ports:
      - "8082:8082"
    env_file:
      - .env
#    depends_on:
#      - user-db

#  product-db:
#    container_name: product-db
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: fosrootpassword
#      MYSQL_DATABASE: productdb
#      MYSQL_USER: fosuser
#      MYSQL_PASSWORD: fospassword
#
#
#  order-db:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: fosrootpassword
#      MYSQL_DATABASE: orderdb
#      MYSQL_USER: fosuser
#      MYSQL_PASSWORD: fospassword
#
#
#  user-db:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: fosrootpassword
#      MYSQL_DATABASE: userdb
#      MYSQL_USER: fosuser
#      MYSQL_PASSWORD: fospassword

